# Simple Trilium instance to use for testing.
services:
  trilium:
    image: triliumnext/trilium:v0.103.0
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - "8080:8080"
    volumes:
      - ./.trilium_data:/home/node/trilium-data
