@startuml entity-state

hide footbox

participant CLEAN
participant CREATE
participant UPDATE
participant DELETE

CLEAN --> UPDATE : setattr()
CLEAN --> DELETE : delete()
CREATE --> DELETE : delete()
UPDATE --> DELETE : delete()
CREATE --> CLEAN : flush()/invalidate()
UPDATE --> CLEAN : flush()/invalidate()
DELETE --> CLEAN : flush()/invalidate()

@enduml
